server {
    listen 81;
    server_name localhost;
    root /var/www/app/backend/web;
    index index.php;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location /uploads/ {
        alias /var/www/app/uploads/;
        expires 365d;
        access_log off;
    }

    location ~ ^/(assets|asset)/ {
        expires max;
        access_log off;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php:9000;
        try_files $uri =404;
    }

    location ~* /\. {
        deny all;
    }
}